### ISSUE TITLE
Wald Beta calculation error: diag requires an array of at least two dimensions

### ISSUE THREAD

**Issue by Yizhang-Li** [bkelly-lab/ipca#11]
self.Gamma[l, :].dot(self.Gamma[l, :].T) returns value instead of the matrix.
![image](https://user-images.githubusercontent.com/26586494/115648959-667b2b00-a2f4-11eb-8b5f-bb3dd9123c33.png)

My env:
Python 3.8.5
pandas 0.25.3
numpy 1.18.4

**Comment by matbuechner** [comment]
Pypi distribution update now as well.
