### ISSUE TITLE
UnboundLocalError: local variable 'L' referenced before assignment

### ISSUE THREAD

**Issue by Elitack** [bkelly-lab/ipca#12]
![image](https://user-images.githubusercontent.com/17812876/130081722-e3b8165d-2946-4dc6-8b6a-06f816a217ce.png)

![image](https://user-images.githubusercontent.com/17812876/130081788-e3cb9205-3592-416c-aa35-124250f680e8.png)

When x is not None, in line 448, it does not initialize L, which will throw the error when predict with portfolio type

**Comment by lbybee** [comment]
This should be fixed with https://github.com/bkelly-lab/ipca/commit/333de14fe3d9e4771667fae8476a6b2509370b6b.  Closing.
