### ISSUE TITLE
How could we verify the solution of IPCA is correct or not?

### ISSUE THREAD

**Issue by KendrickQ** [bkelly-lab/ipca#17]
Hi guys,

Thanks for your kind sharing of this awesome package. However, when I checked the function of test_ipca.py file, I think there are some kinds of testing about whether these functions work or not. 

I tried to generate Gamma, Factors by myself and then compared with the Gamma solved by this package. I think these two matrices are not identical. Therefore, is there any method for me to check the correctness of this package? Look forward to your reply.

Best.

**Comment by kellybry** [comment]
they should be identical as long as you generate \Gamma and F that satisfy
the identification assumptions (and of course assuming you have a large
enough sample to converge on truth).  if not, you will recover the true
fitted values, but a rotated version of \Gamma and F


Bryan T. Kelly
Professor of Finance
Yale School of Management

https://www.bryankellyacademic.org/
https://jkpfactors.com/

**Comment by KendrickQ** [comment]
Hi Bryan,

Thank you so much for your kind reply! 

Actually, I did set up the identification assumptions about \Gamma when I utilized a small case to verify the result. The colab link is https://colab.research.google.com/drive/1Zv8dFXD9S2BdYJ-9CM-YnvtW3eAujnjt?usp=sharing . I listed my data generation process inside the code. 

Even though the model has a score close to 100, the estimated \Gamma is not identical to the pre-specified one. I wonder whether I missed some kinds of assumptions?

Besides, if I apply the characteristic orthogonalization to my features, I also got a different result compared with close-form solution about \Gamma. Because I think I may miss some important assumptions about this model, I didn't add this part inside my code. If you are interested, I could provide my testing result to you.

Best,
Kendrick

**Comment by lbybee** [comment]
Hi Kendrick,

I did a quick skim of your code, I can't say with certainty where the difference is coming from, but it does look like your handling of the orthogonality conditions may be different from ours.  You can check out what's going on under the hood in more detail with the _ALS_fit_portfolio on line 1038-1129 of ipca.py.  Again, can't say with certainly that this is where the difference is, but I'd encourage you to check out that part of the code in detail.

One other thing I will add: while we're not currently maintaining benchmarks against alternative IPCA implementations, when we were initially writing the code we did run some comparisons with an earlier Python implementation as well as a Matlab implementation to verify the estimates were the same.

-Leland

**Comment by KendrickQ** [comment]
Hi Leland,

Thanks for your suggestions! I will check the details of this model implementation. If you could show me more construction details about the orthogonality of IPCA model, I will appreciate it so much!

Best,
Kendrick

**Comment by lbybee** [comment]
I'd point you to the main paper's model and estimation section for the details of the orthogonality constraints, but lines 1106-1128 are the code that enforces the actual conditions.  If you can understand those lines of code and how they relate to the corresponding paragraph (or two) in the paper you should be good.

One other thing I'll suggest is that if you fork the code you could turn off the orthogonalization all together to test whether your ALS procedure is giving the same results as ours.

Regardless, I'm closing this for now but feel free to open if there are other issues or if you want to take a crack at writing up a more comprehensive set of benchmarks against alternative code.

**Comment by KendrickQ** [comment]
Hi Leland,

Thanks for your instruction. After taking the orthogonality constraints shown in the ipca.py file, I could get the matching results using the previous coding file. Thank you so much for your time to help me out.

What's more, I am still curious about applying characteristic orthogonalization cross-sectionally. I tried this method recommended in the appendix B of paper "Characteristics Are Covariances". My question is, if applying Gram-Schmidt process in instrument matrix Zt cross-sectionally, what remains the same as using Zt without orthogonality? I think the \Gamma and factors will be changed if applying orthogonality to original characteristic matrix.

Look forward to your reply. I am really appreciated for your help.

Best,
Kendrick

**Comment by kellybry** [comment]
Hi Kendrick,

Thanks for your interest.  You will have to dive into these questions on
your own.  Let us know if you have any other issues with the code.

Bryan



Bryan T. Kelly
Professor of Finance
Yale School of Management

https://www.bryankellyacademic.org/
https://jkpfactors.com/

**Comment by KendrickQ** [comment]
Hi Bryan,

Thank you for your reply! It did help me a lot to dive deep into this code. I think there is a typo inside the ipca.py about parameters `n_jobs` and `backend`. In line 1082 of ipca.py file, I think it is better to use `n_jobs = self.n_jobs` and `backend=self.backend`.

Besides, I wonder if this ALS method's estimation result is a global minimum of this objective function. If not, how should we convince ourselves about using SVD decomposition initialization of \Gamma is a good method in some specific contexts?

Best,
Kendrick
